name: Web Terminal

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install ttyd
        run: |
          sudo apt update
          sudo apt install -y ttyd

      - name: Start terminal
        run: |
          ttyd -p 9000 -W bash &

      - name: Create tunnel
        run: |
          ssh -p 443 -o StrictHostKeyChecking=no -R0:localhost:9000 a.pinggy.io
          
      - name: Keep alive
        run: |
          while true; do sleep 300; done
